name: frappe_client
resolution: workspace
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ^3.38.9

dependencies:
  app_logger:
    path: ../app_logger
  dio: ^5.9.2
  equatable: ^2.0.8
  socket_io_client: ^3.1.4
  flutter:
    sdk: flutter
  frappe_dart:
    git:
      url: https://github.com/kinetsystems/frappe_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
